### ISSUE TITLE
Hatch Content (comms)

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#143]
## 📋 Anything to add?
For all issues related to content pre-Hatch.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by drllau** [comment]
Need to add message that anyone participating in hatch will become a member of Common Stack for legal protection (otherwise may be treated as private business partnership and taxed as such), a swiss unregistered verein (equiv to unincorporated assoc) and membership dues are expected (500 DAI? ... this sounds high to me)
