### ISSUE TITLE
Add and promote all Commons Stack videos in the TE youtube channel

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#173]
## 🎉 Subtasks

TEC channel
- [x] add playlist “Commons Stack” include :
Commons simulator x 56 (Just include the last 5-10?)
The CS Reviews x 4
Spotlight on Trent x 1
Research Roundup x 9
How the Trusted Seed video x 1 https://www.youtube.com/watch?v=zhq6YsEuLYc&ab_channel=CommonsStack
- [x] Add “End screen” to videos (last 1 video and going froward) to :
Commons Simulator → TEC Lab and Garden Swarm
CS Reviews → Community Call
Spotlight on Trent → TEC Lab, Community Call
Research Roundup → TEC Lab
Trusted Seed video → Community Call

## 🤼‍ Reviewer

@

**Comment by GriffGreen** [comment]
add to social background

**Comment by tamarandom** [comment]
@GriffGreen, @iviangita can take this one. 

What about:
1) playlist for CommonsStack 
2) latest videos (which are the commons simulator, the CS Reviews and the spotlight on Trent.

**Comment by tamarandom** [comment]
Hey @iviangita 

Here's an update : 

Include the Research Roundup and the TEC youtube videos on the Commons Stack channel (these predate the TEC Youtube channel) if they have not already been imported.

Yes to the suggested new video being commons stack based on most views and this one : https://www.youtube.com/watch?v=zhq6YsEuLYc&ab_channel=CommonsStack

**Comment by iviangita** [comment]
Thanks @tamarandom! Our suggestion is to add the CS videos as "end screens" or "cards" in the TEC videos, instead of uploading them on the TEC Youtube channel. 

The end screen looks like this:

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/a3593c3f-e7f8-40a8-bcf2-ded5020c5f73)


The card looks like this:

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/5283a37c-ac03-4a56-bb51-00f8c827229e)

Let us know if these 2 options are okay for you, or if you prefer to upload the CS videos on the TEC Youtube channel :)

cc: @Zeptimus

**Comment by tamarandom** [comment]
Awesome @iviangita !! From our working session just now : 

Youtube Small improvements : 

Commons Stack channel 
[ ] Can the order of the playlists be changed so that the more recent+important ones are at the top. 
[ ] Remove playlist “TEC calls”? The content in that playlist is from Oct 24 and before. 
[ ] Can we add playlist “Commons Stack Reviews”

TEC channel 
[ ] add playlist “Commons Stack” include :
Commons simulator x 56 (Just include the last 5-10?)
The CS Reviews x 4
Spotlight on Trent x 1
Research Roundup  x 9 
How the Trusted Seed video x 1 https://www.youtube.com/watch?v=zhq6YsEuLYc&ab_channel=CommonsStack
[ ] Add “End screen” to videos (last 1 video and going froward) to : 
	Commons Simulator  →  TEC Lab and Garden Swarm 
	CS Reviews → Community Call
	Spotlight on Trent → TEC Lab, Community Call 
	Research Roundup →  TEC Lab 
	Trusted Seed video → Community Call
