### ISSUE TITLE
Figure out if the feasibility of using Token Log to vote on Hatch Params

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#281]

**Comment by LinuxIsCool** [comment]
Call with Wes coming up. Hopefully it works out of the box. Being mindful of the details. Consider issuing tokens for impact hours, and giving each token 50% voting power, normalizing the CSTK tokens, and .. and issuing a new token to represent that power, and use that token to vote in token log. Or just impact hours token and play with the weights in the backend of the tokenlog. Tokenlog is open source, so we can make issues directly on that repository. We then vote on it, and if accetped (to the tokenlog thing), then, that will happen in parallel as we are building out the models and people will start voting on it. We will pick a date, at that date, the highest votes we go with. We will likely do a test hatch, 2 or 3 days, depends on how things are for the second rehearsal, and then we launch. 

We have to use tokenlog within github to vote on the hatch parameters. There will be proposals there, and people can vote. A list of proposals for parameters, and everyone will be able to use their CSTK and impact hours to vote, and we will use quadratic voting so that people vote for the ones they want, perhaps up to 5 votes. We are considering minting a new token for this process. Wes will be super helpful in deciding these details. In an ideal world, we wouldn't have to mint a new token. Probably normalize in the backend on tokenlog.

**Comment by freedumbs00** [comment]
Coordinated with Wesley on multiple tokens on Token Log.  He has to do some work to make the balance between Cstack and IH but he thinks he can do it.  He is looking for help in that area with contributions from other devs.

**Comment by freedumbs00** [comment]
https://deploy-preview-16--tokenlog.netlify.app/TECommons/coordination

Has been feasible.  Now we only need to determine Params and create issues.
