### ISSUE TITLE
Proofreading and checking all links

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#324]

**Comment by markoprljic** [comment]
@jessicazartler @freedumbs00 
You can go ahead and proofread the draft site here https://tecommons.org/?page_id=380

Once you're done please submit a bullet list of revisions (if any) in the comment of this issue.
Thanks.

**Comment by jessicazartler** [comment]
Looks great! Some feedback, links & CTAs:

-I think we should bring back our tagline under TEC at the top like we had "‌Sustainable‌ ‌&‌ ‌Ethical‌ ‌Design‌ ‌for‌ ‌Token‌ ‌Ecosystems‌" ‌

-I think the definition section text can be a bit bigger to fill the space a little more

-Overall, there are way too many CTAs - I think we should have two at the top right -- JOIN US / STAY UPDATED
Join us can link to our new Discord --> https://discord.gg/tgN4V43H9U
Stay updated should link to an email sign up form that goes to our CRM

-DELETE Build with us CTA
-DELETE Join the mission CTA
-DELETE 2nd Build with us CTA
-Join the Community should link here --> https://forum.tecommons.org/t/5-how-to-join-contribute/98

DELETE Join the Ecosystem CTA --- REPLACE w/ FOLLOW US 

Let me know if you have any other questions, otherwise, looks great let's rolll!

**Comment by markoprljic** [comment]
> -I think we should bring back our tagline under TEC at the top like we had "‌Sustainable‌ ‌&‌ ‌Ethical‌ ‌Design‌ ‌for‌ ‌Token‌ ‌Ecosystems‌" ‌

Yes!

> 
> -I think the definition section text can be a bit bigger to fill the space a little more

No, it was meant to be this way in the original design.

> 
> -Overall, there are way too many CTAs -

I  don't think the same. Each CTA is meant to be present on every section on the landing page, they all link to the forum.

Subscribe to updates will be added in the footer and that is linked directly to our Hubspot.
