### ISSUE TITLE
Add the T&C's to the Discord

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#413]
## 📋 Anything to add?

Once the Discord T&C's are approved by @Santigs, @JuankBell , @liviade1, @Zeptimus  then we need to make sure everyone signs them before they join the server.

This issue is for implementing that process in the discord, it is a blocker for launching the discord. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by metaverde** [comment]
Planning to put the T and C in the #🌈welcome channel on the TEC Discord.

**Comment by metaverde** [comment]
This is complete.
I'm not seeing how to close the issue.

**Comment by tamarandom** [comment]
Hey @metaverde. Hmmm. It might be due to permissions. I'm seeing that there is a pending invite for your account in this repo. Let me try deleting it and re-adding you. I just did it so let me know if you have the new invite and can close it now! (Github changes can take time so if it's not working tomorrow, let me know)

![Screen Shot 2021-02-18 at 9.48.43 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/eba9a56c-f549-4200-a4bf-6b6fe0f2096d)

**Comment by tamarandom** [comment]
Update : Closed!
