### ISSUE TITLE
Prepare Gravity presentation for Metafest

### ISSUE THREAD

**Issue by JuankBell** [TECommons/coordination#543]
## 📋 Anything to add?

Make a selection of the Graviton training slides https://docs.google.com/presentation/d/15UvsnS9oX5czAKIGHZUqJLhrORpPebWsZeCqmUz9BUE/edit#slide=id.gb55e79f42e_0_114 

to present in the Metafest 

Wednesday 24th march, 1pm EST-7pm CET

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by JuankBell** [comment]
Slides -> https://docs.google.com/presentation/d/17L90oBGdVHCCGAzdnGI7JM7Um9LqYIrBtExN-QOs36Y/edit?usp=sharing

Tweet:

Today, Wednesday 24th of march, at 12:15 EST / 17:45 CET. @bellcho will lead a Gravity workshop to the @MetaFam, all people is invited to know more about this project from the @Tecmns and promote Alternative Dispute Resolution as something relevant in decentralized communities!

Jump into -> https://metafest.metagame.wtf/

![Captura de Pantalla 2021-03-23 a la(s) 3.52.51 p. m..png](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/66f0d8c8-6034-4802-8708-503232548d01)

**Comment by iviangita** [comment]
@JuankBell I revised it because Twitter has limited characters and also changed the graphic because the schedule doesn't match the time of the workshop. Let me know if this is good for you or if there's anything you want to change :)

TWEET:

Today March 24 12:15pm EST / 5:15pm CET, our Gravity steward @bellcho leads a Gravity workshop for @MetaFam and talks about Alternative Dispute Resolution as something relevant in decentralized communities! 👨‍🚀🚀

Jump into -> https://metafest.metagame.wtf/

Everybody is welcome! 🌈

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/285959d3-c29b-4698-89cc-0cb450273427)![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/4fb0124b-e7c6-47a6-aac1-978c3b8996b4)

**Comment by JuankBell** [comment]
The presentation went well, thanks everyone who made it possible, the Metagame crew, Jess, Tam, Ivy, Metaverde.
The video has been uploaded in the Metamedia youtube.
This were the slides.
https://docs.google.com/presentation/d/17L90oBGdVHCCGAzdnGI7JM7Um9LqYIrBtExN-QOs36Y/edit#slide=id.gc799d5c135_2_767
