### ISSUE TITLE
Update Gitbook with WG Information

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#561]
All Stewards please update Gitbook WG sections with information about each WG. 
Don't stop there! Update other info you see that needs to be added to the Gitbook.

https://app.gitbook.com/@token-engineering-commons/s/tec-handbook/

Once you're done please remove yourself as an assignee from this issue and leave a comment to inform others.
Thanks!

**Comment by tamarandom** [comment]
Hey @markoprljic ! Appreciate your enthusiasm but have you engaged in advice process with @liviade1 on this yet? She and I have started the conversation about what WG content should be in Gitbook versus Forum, and then where it would go. It would be best to continue to allow her to manage this so that it can be done in a more organized fashion.  

I'm going to close this issue as that task is covered under #512 already. Please feel free to add any suggestions you have there.

**Comment by markoprljic** [comment]
Perfect then. Wasn't aware of the discussion you had.
Thanks.
